'use strict';

/* Add All Action constants here  */

//ACCOUNTS ACTIONS
const Actions = {
    //GENERIC ACTION
    FETCHING_REQUEST: 'FETCH_REQUEST',
    RECEIVED_REQUEST: 'RECEIVED_REQUEST',

    //Home Actions
    FETCHING_WIDGET: 'FETCHING_WIDGET',
    HIDE_SEARCH_BAR: 'HIDE_SEARCH_BAR',
    WIDGET_RECEIVED: 'WIDGET_RECEIVED',
    WIDGET_RECEIVED_ERROR: 'WIDGET_RECEIVED_ERROR',
    CLEAR_HOME_DATA:'CLEAR_HOME_DATA',

    //Account Actions
    BEGIN_LOGIN: 'BEGIN_LOGIN',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',
    FETCH_USER_DATA: 'FETCH_USER_DATA',
    BEGIN_LOGOUT: 'BEGIN_LOGOUT',
    BEGIN_CHECK_EMAIL_EXISTENCE: 'BEGIN_CHECK_EMAIL_EXISTENCE_API',
    CHECK_EMAIL_EXISTENCE_SUCCESS: 'CHECK_EMAIL_EXISTENCE_API_SUCCESS',
    CHECK_EMAIL_EXISTENCE_FAILURE: 'CHECK_EMAIL_EXISTENCE_API_FAILURE',
    BEGIN_MOBILE_VERIFY_API: 'BEGIN_MOBILE_VERIFICATION_CODE_API',
    MOBILE_API_VERIFY_SUCCESS: 'MOBILE_VERIFICATION_CODE_API_SUCCESS',
    MOBILE_VERIFICATION_CODE_API_FAILURE: 'MOBILE_VERIFICATION_CODE_API_FAILURE',
    BEGIN_SOCIAL_LOGIN_API: 'BEGIN_SOCIAL_LOGIN_API',
    SOCIAL_LOGIN_API_SUCCESS: 'SOCIAL_LOGIN_API_SUCCESS',
    SOCIAL_LOGIN_API_FAILURE: 'SOCIAL_LOGIN_API_FAILURE',
    BEGIN_PASSWORD_REQUEST_API: 'BEGIN_PASSWORD_REQUEST_API',
    PASSWORD_REQUEST_API_SUCCESS: 'PASSWORD_REQUEST_API_SUCCESS',
    PASSWORD_REQUEST_API_FAILURE: 'PASSWORD_REQUEST_API_FAILURE',
    TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
    HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',
    BEGIN_AUTHENTICATION_LOADER: 'BEGIN_AUTHENTICATION_LOADER',
    STOP_AUTHENTICATION_LOADER: 'STOP_AUTHENTICATION_LOADER',
    SET_COUNTRY_CODE: 'SET_COUNTRY_CODE',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    SAVE_TEMP_NUMBER: 'SAVE_TEMP_NUMBER',
    GET_ADDRESS_START: 'GET_ADDRESS_START',
    GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAIL: 'GET_ADDRESS_FAIL',
    ADD_ADDRESS_START: 'ADD_ADDRESS_START',
    ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAIL: 'ADD_ADDRESS_FAIL',
    REMOVE_TEMP_NUMBER: 'REMOVE_TEMP_NUMBER',
    SET_GROCERY_CITY: 'SET_GROCERY_CITY',
    SET_DEVICE_INFO: 'SET_DEVICE_INFO',


    //SEARCH ACTIONS
    FETCHING_PRODUCT: 'FETCHING_PRODUCT',
    PRODUCT_RECEIVED: 'PRODUCT_RECEIVED',
    PRODUCT_ERROR: 'PRODUCT_ERROR',
    CLEAR_PRODUCT_DATA:'CLEAR_PRODUCT_DATA',
    

    //plp
    SORT_SELECTED: 'SORT_SELECTED',
    SIZE_SELECTED: 'SIZE_SELECTED',
    QUANTITY_SELECTED: 'QUANTITY_SELECTED',

    //carousel products;
    GET_CAROUSEL_PRODUCTS: 'GET_CAROUSEL_PRODUCTS',
    CAROUSEL_PRODUCTS_SUCCESS: 'CAROUSEL_PRODUCTS_SUCCESS',

    //HAMBURGER ACTIONS
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED',
    FETCH_CATEGORIES_RECEIVED: 'FETCH_CATEGORIES_RECEIVED',

    //product detail
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
    GET_PRODUCT_DETAIL_ERROR: 'GET_PRODUCT_DETAIL_ERROR',
    GET_PDP_DELIVERY_DETAILS: 'GET_PDP_DELIVERY_DETAILS',


    //filters
    GET_FILTERS: 'GET_FILTERS',
    GET_FILTERS_SUCCESS: 'GET_FILTERS_SUCCESS',
    GET_FILTERS_ERROR: 'GET_FILTERS_ERROR',
    FILTER_APPLIED: 'FILTER_APPLIED',
    CLEAR_FILTER:'CLEAR_FILTER',

    //cart actions
    BEGIN_PRODUCT_REVIEW: 'BEGIN_PRODUCT_REVIEW',
    PRODUCT_REVIEW_SUCCESS: 'PRODUCT_REVIEW_SUCCESS',
    PRODUCT_REVIEW_FAILURE: 'PRODUCT_REVIEW_FAILURE',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    FETCH_CART: 'FETCH_CART',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
    UPDATE_PRODUCT_IN_CART: 'UPDATE_PRODUCT_IN_CART',
    REPLACE_PRODUCT_IN_CART:'REPLACE_PRODUCT_IN_CART',
    UPDATE_CART_STATUS: 'UPDATE_CART_STATUS',
    REMOVE_PRODUCTS_FROM_CART: 'REMOVE_PRODUCTS_FROM_CART',
    ON_ORDER_PLACED:'ON_ORDER_PLACED',
    GET_CART_ITEM_DATA:'GET_CART_ITEM_DATA',
    UPDATE_CART_ITEM_DATA:'UPDATE_CART_ITEM_DATA',
    //CART_ERROR:'CART_ERROR',

    //checkout actions

    ORDER_SUCCESS: 'ORDER_SUCCESS',
    ORDER_FAILURE: 'ORDER_FAILURE',
    CHECKOUT_EVENTS:'CHECKOUT_EVENTS',
    BEGIN_CHECKOUT: 'BEGIN_CHECKOUT',
    CHECKOUT_STEP_2: 'CHECKOUT_STEP_2',

    //Algolia Search
    FETCH_SEARCH_AUTOCOMPLETE_START: 'FETCH_SEARCH_AUTOCOMPLETE_START',
    FETCH_SEARCH_AUTOCOMPLETE_RECEIVED: 'FETCH_SEARCH_AUTOCOMPLETE_RECEIVED',
    FETCH_SEARCH_RESULT_START: 'FETCH_SEARCH_RESULT_START',
    FETCH_SEARCH_RESULT_FAILED: 'FETCH_SEARCH_RESULT_FAILED',
    FETCH_SEARCH_RESULT_RECEIVED: 'FETCH_SEARCH_RESULT_RECEIVED',


    //config API Reducer
    GET_CONFIG: 'GET_CONFIG',
    SET_CONFIG: 'SET_CONFIG',
    DELETE_CONFIG: 'DELETE_CONFIG',
    SET_SELECTED_LANGUAGE: 'SET_SELECTED_LANGUAGE',
    SET_SELECTED_COUNTRY: 'SET_SELECTED_COUNTRY',
    RESET_APP_COUNTRY_LANGUAGE: 'RESET_APP_COUNTRY_LANGUAGE',

    // Feature map API
    GET_FEATURE_MAP: 'GET_FEATURE_MAP',
    SET_FEATURE_MAP: 'SET_FEATURE_MAP',
    DELETE_FEATURE_MAP: 'DELETE_FEATURE_MAP',

    //globals
    DEEP_LINK: 'DEEP_LINK',
    TRACKING: 'TRACKING',

    // selected city
    SET_SELECTED_CITY: 'SET_SELECTED_CITY',
    DELETE_SELECTED_CITY: 'DELETE_SELECTED_CITY',

    // saved cards
    GET_CARDS_REQUEST: 'GET_CARDS_REQUEST',
    GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
    GET_CARDS_FAIL: 'GET_CARDS_FAIL',

    //MSD actions
    CAROUSAL_PRODUCT_CLICK: 'CAROUSAL_PRODUCT_CLICK',
    CAROUSAL_SWIPE: 'CAROUSAL_SWIPE',

    //
    UPDATE_SCREEN_NAME:'UPDATE_SCREEN_NAME',
    FIRST_TIME_LAUNCH:'FIRST_TIME_LAUNCH',
    SAVE_INITIAL_DEEPLINK_URL:'SAVE_INITIAL_DEEPLINK_URL',

    //rating reviews
    FETCHED_RATING_REVIEWS:'FETCHED_RATING_REVIEWS'

};

export default Actions;