inhibit_all_warnings!
use_frameworks!

target :Wadi do
    pod 'HockeySDK'
    pod 'CocoaLumberjack'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'Google/SignIn'
    pod 'Tune' #, :git => 'https://github.com/smartwhere/tune-ios-sdk.git', :tag => '4.13.3'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
    pod 'Appsee'
    pod 'GoogleTagManager', '~> 3.15.0'
    pod 'Google/Analytics'
    pod 'GoogleIDFASupport'
    pod 'SmartWhereSDK', '~> 17.258.3’
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
    pod 'GCDWebServer', '~> 3.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MoEngage-iOS-SDK'
end
