//Screen ids constants
export const screens = {
    Category: 'Category',
    Home: 'Home',
    MockableHome:'Home-v2',
    CategoryToHome:'CategoryToHome',
    Search: 'Search',
    SearchFilters:'SearchFilters',
    Cart: 'Cart',
    Account: 'Account',
    Login: 'LoginStack',
    Authentication:'Authentication',
    LoginPage:'LoginPage',
    SignupScreen:'SignupScreen',
    PhoneScreen:'PhoneScreen',
    OTPScreen:'OTPScreen',
    PasswordScreen:'PasswordScreen',
    ForgotPasswordScreen:'ForgotPasswordScreen',
    SignupSuccessScreen:'SignupSuccessScreen',
    Country: 'Country',
    MailLogin: 'MailLogin',
    ProductList: 'ProductList',
    ProductListGrocery:'ProductListGrocery',
    Language: 'Language',
    //ErrorView : 'HomeStackPop',
    ErrorView:'ErrorView',
    CountryView:'CountryView',
    LanguageView:'LanguageView',
    ProductDetail:'ProductDetail',
    MultiSeller:'MultiSeller',
    Checkout:'Checkout',
    DeliverySlots: 'Delivery',
    MyOrders: 'MyOrders',
    Wallet:'Wallet',
    OrderDetails: 'OrderDetailsScreen',
    AccountsWebView: 'AccountsWebView',
    DoodleWebHelperView: 'DoodleWebHelperView',
    CitySelectionScreen:'CitySelectionScreen',

    HomeToPdp: 'HomeToPdp',
    HomeToPlp: 'HomeToPlp',
    SearchToPdp: 'SearchToPdp',
    SearchToPlp: 'SearchToPlp',
    CartToCheckout: 'CartToCheckout',
    CartToPdp:'CartToPdp',
    PlpToPdp:'PlpToPdp',
    AccountsToWebView : 'AccountsToWebView',
    Filter:'Filter',
    SizeChart: 'SizeChart',
    AddressPage: 'AccountsAddressScreen',
    EditAddressPage: 'AccountsAddressEditScreen',
    CreditCardScreen: 'CreditCardScreen',
    SplashScreen: 'SplashScreen',
    DoodleContainerScreen: 'DoodleContainerScreen',
    HtmlDescription: 'HtmlDescription',
    CartButton: 'CartButton',
    GooglePlaces:'GooglePlaces',
    MapsBackButton:'MapsBackButton',
};